name: Linters

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Ruff
        run: ruff check .
  mypy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Set up Python
          uses: actions/setup-python@v6
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: pip install -r requirements-dev.txt

        - name: Run mypy (type checking)
          run: mypy .